[package]
name = "spotify-parser"
description = "A library for parsing Spotify data."
version = "1.0.1"
edition = "2021"
license-file = "LICENSE.md"
repository = "https://github.com/eRgo35/spotify-parser"
readme = "README.md"
keywords = ["spotify", "parser", "embed", "library"]
categories = ["parsing"]

[dependencies]
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["blocking", "rustls-tls"] }
scraper = "0.19.1"
serde = "1.0.204"
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["macros"] }
